### ISSUE TITLE
Not running on Apple M1 

### ISSUE THREAD

**Issue by minaeann** [anitagraser/movingpandas#99]
Hello! I am having troubles to run movingpandas on MacOs Big Sur (v. 11.0) with Apple M1 chip. 

First I successfully create an environment:

`conda create -n new-env python=3.8`

Then, I activate it:

`conda activate new-env`

Next, the movingpandas are installed without errors:

`conda install -c conda-forge movingpandas`

However, when I run:

`python3 -c "import movingpandas"`

the result is:

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/miniconda3/envs/new-env/lib/python3.8/site-packages/movingpandas/__init__.py", line 5, in <module>
    from .trajectory import Trajectory
  File "/home/miniconda3/envs/new-env/lib/python3.8/site-packages/movingpandas/trajectory.py", line 10, in <module>
    from geopandas import GeoDataFrame
  File "/home/miniconda3/envs/new-env/lib/python3.8/site-packages/geopandas/__init__.py", line 7, in <module>
    from geopandas.io.file import _read_file as read_file  # noqa
  File "/home/miniconda3/envs/new-env/lib/python3.8/site-packages/geopandas/io/file.py", line 7, in <module>
    import fiona
  File "/home/miniconda3/envs/new-env/lib/python3.8/site-packages/fiona/__init__.py", line 84, in <module>
    from fiona.collection import BytesCollection, Collection
  File "/home/miniconda3/envs/new-env/lib/python3.8/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: dlopen(/home/miniconda3/envs/new-env/lib/python3.8/site-packages/fiona/ogrext.cpython-38-darwin.so, 2): 
Library not loaded: @rpath/libtbb.dylib
Referenced from: /home/miniconda3/envs/new-env/lib/libtiledb.dylib
  Reason: image not found`

**Comment by anitagraser** [comment]
Looks like an upstream issue with GeoPandas / Fiona. Can you install and use these libraries without MovingPandas?

**Comment by minaeann** [comment]
No, I cannot. Thank you for the response.
